/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import ChangePassword.ChangePassword;
import Companies.Company;
import CreateUser.CreateUser;
import Medicines.Medicine;
import NewSalesRecord.NewSalesRecord;
import ProductCategory.AddCategory;
import SalesRecord.SalesRecord;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author hp
 */
public class MainActivity extends javax.swing.JFrame {
    Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;

    /**
     * Creates new form MainActivity
     */
    public MainActivity() {
        initComponents();
        conn = ConnectionToDB.connectToDb();
        this.setSize(1400, 800);
        updateTable();
        
    }
    
 
    private void updateTable(){
   
        try{
          String sql = "SELECT  product_name as 'Product Name',company_name as 'Company Name',product_category as 'Product Category',quantity as 'Quantity',price_per_unit as 'Price Per Unit' FROM products";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            medicineTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medicinesBtn = new javax.swing.JButton();
        companiesBtn = new javax.swing.JButton();
        viewSalesRecordBtn = new javax.swing.JButton();
        newSalesBtn = new javax.swing.JButton();
        addProductCtgBtn = new javax.swing.JButton();
        createuserBtn = new javax.swing.JButton();
        changePswdBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loggedinText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicineTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("Medical Store MAnagement System");

        medicinesBtn.setText("Medicines");
        medicinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinesBtnActionPerformed(evt);
            }
        });

        companiesBtn.setText("Companies");
        companiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiesBtnActionPerformed(evt);
            }
        });

        viewSalesRecordBtn.setText("View Sale records");
        viewSalesRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesRecordBtnActionPerformed(evt);
            }
        });

        newSalesBtn.setText("New Sales");
        newSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalesBtnActionPerformed(evt);
            }
        });

        addProductCtgBtn.setText("Add New Product Category");
        addProductCtgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductCtgBtnActionPerformed(evt);
            }
        });

        createuserBtn.setText("Create User");
        createuserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createuserBtnActionPerformed(evt);
            }
        });

        changePswdBtn.setText("Change Pasword");
        changePswdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePswdBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Search Product    :");

        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtKeyReleased(evt);
            }
        });

        jLabel3.setText("Logged in as    :");

        loggedinText.setForeground(new java.awt.Color(255, 51, 51));
        loggedinText.setText("Logged in as");

        medicineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(medicineTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addProductCtgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medicinesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companiesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewSalesRecordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newSalesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createuserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changePswdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(350, 350, 350)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(loggedinText))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3)
                    .addComponent(loggedinText))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(medicinesBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(companiesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewSalesRecordBtn)
                        .addGap(18, 18, 18)
                        .addComponent(newSalesBtn)
                        .addGap(18, 18, 18)
                        .addComponent(addProductCtgBtn)
                        .addGap(18, 18, 18)
                        .addComponent(createuserBtn)
                        .addGap(18, 18, 18)
                        .addComponent(changePswdBtn)
                        .addGap(18, 18, 18)
                        .addComponent(logoutBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductCtgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductCtgBtnActionPerformed
        // TODO add your handling code here:
        ProductCategory.AddCategory ac = new AddCategory();
        ac.setVisible(true);
    }//GEN-LAST:event_addProductCtgBtnActionPerformed

    private void createuserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createuserBtnActionPerformed
        // TODO add your handling code here:
        CreateUser createUser = new CreateUser();
        createUser.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
    }//GEN-LAST:event_createuserBtnActionPerformed

    private void changePswdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePswdBtnActionPerformed
        // TODO add your handling code here:
        ChangePassword cp = new ChangePassword();       
        cp.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
    }//GEN-LAST:event_changePswdBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void searchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyReleased
        // TODO add your handling code here:
        try{
          String sql = "SELECT  product_name as 'Product Name',company_name as 'Company Name',product_category as 'Product Category',quantity as 'Quantity',price_per_unit as 'Price Per Unit' FROM products WHERE product_name LIKE '%"+ searchTxt.getText() +"%'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            medicineTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_searchTxtKeyReleased

    private void medicinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinesBtnActionPerformed
        // TODO add your handling code here:
        Medicines.Medicine m = new Medicine();
        m.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
        
    }//GEN-LAST:event_medicinesBtnActionPerformed

    private void companiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiesBtnActionPerformed
        // TODO add your handling code here:
        Companies.Company c = new Company();
        c.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
    }//GEN-LAST:event_companiesBtnActionPerformed

    private void viewSalesRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesRecordBtnActionPerformed
        // TODO add your handling code here:
        SalesRecord sr = new SalesRecord();        
        sr.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
    }//GEN-LAST:event_viewSalesRecordBtnActionPerformed

    private void newSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalesBtnActionPerformed
        // TODO add your handling code here:
        NewSalesRecord nsr = new NewSalesRecord();
        nsr.setVisible(true);
        setVisible(false);
            setDefaultCloseOperation(EXIT_ON_CLOSE);
            dispose();
    }//GEN-LAST:event_newSalesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductCtgBtn;
    private javax.swing.JButton changePswdBtn;
    private javax.swing.JButton companiesBtn;
    private javax.swing.JButton createuserBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel loggedinText;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTable medicineTable;
    private javax.swing.JButton medicinesBtn;
    private javax.swing.JButton newSalesBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JButton viewSalesRecordBtn;
    // End of variables declaration//GEN-END:variables
}
